jqchat/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import *

import views

urlpatterns = patterns('',
    # Example chat room.
    url(r"room/(?P<id>\d+)/$", views.window, name="jqchat_test_window"),
    url(r"room/(?P<id>\d+)/ajax/$", views.BasicAjaxHandler, name="jqchat_ajax"),
    # Second example room - adds room descriptions.
    url(r"room_with_description/(?P<id>\d+)/$", views.WindowWithDescription, name="jqchat_test_window_with_description"),
    url(r"room_with_description/(?P<id>\d+)/ajax/$", views.WindowWithDescriptionAjaxHandler, name="jqchat_test_window_with_description_ajax"),
)

jqchat/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.template import Context
from django.template.loader import get_template
from django.conf import settings

import datetime
import time


class Room(models.Model):
    """Conversations can take place in one of many rooms.

    >>> l = Room(name='Test room')
    >>> l.save()
    >>> l
    <Room: Test room>

    Note that updating 'description' auto-updates 'description_modified' when saving:

    >>> l.description_modified

    >>> l.description = 'A description'

    Note that we need to always set the 'user' attribute as a system message is generated for each change.
    >>> l.user = User.objects.get(id=1)
    >>> l.save()

    # description_modified is a unix timestamp.
    >>> m = l.description_modified
    >>> m > 0
    True

    """
    name = models.CharField(max_length=20, null=True, blank=True, help_text='Name of the room.')
    created = models.DateTimeField(editable=False)
    description = models.CharField(max_length=100, null=True, blank=True, help_text='The description of this room.')
    description_modified = models.IntegerField(null=True, editable=False, help_text='Unix timestamp when the description was created or last modified.')
    last_activity = models.IntegerField(editable=False,
                                        help_text='Last activity in the room. Stored as a Unix timestamp.')
    # Define generic relation to target object. This is optional.
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    content_object = generic.GenericForeignKey()

    def __unicode__(self):
        return u'%s' % (self.name)

    class Meta:
        ordering = ['created']

    def __init__(self, *args, **kw):
        super(Room, self).__init__(*args, **kw)
        self._init_description = self.description

    def save(self, **kw):
        # If description modified, update the timestamp field.
        if self._init_description != self.description:
            self.description_modified = time.time()
        # if last_activity is null (i.e. we are creating the room) set it to now.
        if not self.last_activity:
            self.last_activity = time.time()
        if not self.created:
            self.created = datetime.datetime.now()
        super(Room, self).save(**kw)

    @property
    def last_activity_formatted(self):
        """Return Unix timestamp, then express it as a time."""
        return display_timestamp(self.last_activity)

    @property
    def last_activity_datetime(self):
        """Convert last_activity into a datetime object (used to feed into timesince
        filter tag, ideally I should send a patch to Django to accept Unix times)"""
        return datetime.datetime.fromtimestamp(self.last_activity)

# The list of events can be customised for each project.
try:
    EVENT_CHOICES = settings.JQCHAT_EVENT_CHOICES
except:
    # Use default event list.
    EVENT_CHOICES = (
                  (1, "has changed the room's description."),
                  (2, "has joined the room."),
                  (3, "has left the room."),
                 )
class messageManager(models.Manager):

    def create_message(self, user, room, msg):
        """Create a message for the given user."""
        message_template = get_template('jqchat/chat_message.html')
        raw_text = message_template.render(Context({'user': user, 'msg': msg}))
        # Clean html before save to db
        text = ''.join(raw_text.replace('"', "'").split('\n')).strip().replace('\t', '')
        m = Message.objects.create(user=user, room=room, text=text)
        return m

    def create_event(self, user, room, event_id):
        """Create an event for the given user."""
        m = Message(user=user, room=room, event=event_id)
        message_template = get_template('jqchat/chat_event.html')
        raw_text = message_template.render(Context({'user': user, 'event': m.get_event_display()}))
        # Clean html before save to db
        m.text = ''.join(raw_text.replace('"', "'").split('\n')).strip().replace('\t', '')
        m.save()
        return m

class Message(models.Model):
    """Messages displayed in the chat client.

    Note that we have 2 categories of messages:
    - a text typed in by the user.
    - an event carried out in the room ("user X has left the room.").

    New messages should be created through the supplied manager methods, as all
    messages get preformatted (added markup) for display in the chat window.
    For example:

    Messages:
    >>> user = User.objects.create_user('john', 'lennon@thebeatles.com', 'johnpassword')
    >>> room = Room.objects.create(name='Test room')
    >>> m = Message.objects.create_message(user, room, 'hello there')
    >>> m.text
    '<strong>john</strong> hello there<br />'

    Events:
    >>> m1 = Message.objects.create_event(user, room, 1)
    >>> u'<strong>john</strong> <em>has changed' in m1.text
    True

    Note that there are 2 timestamp fields:
    - a unix timestamp.
    - a datetime timestamp.
    The reason: the unix timestamp is higher performance when sending data to the browser (easier
    and faster to handle numbers instead of datetimes. The 'created' is used for displaying the date
    of messages; I could calculate it from the unix timestamp, but I'm guessing that I will get
    higher performance by storing it in the database.

    """

    user = models.ForeignKey(User, related_name='jchat_messages')
    room = models.ForeignKey(Room, help_text='This message was posted in a given chat room.')
    event = models.IntegerField(null=True, blank=True, choices=EVENT_CHOICES, help_text='An action performed in the room, either by a user or by the system (e.g. XYZ leaves room.')
    text = models.TextField(null=True, blank=True, help_text='A message, either typed in by a user or generated by the system.')
    unix_timestamp = models.FloatField(editable=False, help_text='Unix timestamp when this message was inserted into the database.')
    created = models.DateTimeField(editable=False)
    highlighted = models.BooleanField(default=False)

    def __unicode__(self):
        return u'%s, %s' % (self.user, self.unix_timestamp)

    def save(self, **kw):
        if not self.unix_timestamp:
            self.unix_timestamp = time.time()
            self.created = datetime.datetime.fromtimestamp(self.unix_timestamp)
        super(Message, self).save(**kw)
        self.room.last_activity = int(time.time())
        self.room.save()

    class Meta:
        ordering = ['unix_timestamp']

    objects = messageManager()

class memberManager(models.Manager):

    def remove_member(self, user, room):
        """Remove a room user association"""
        usr_prev_rooms = RoomMember.objects.filter(user=user)
        for prev_room in usr_prev_rooms:
            if prev_room.room == room:
                continue
            Message.objects.create_event(user, prev_room.room, 3)
        usr_prev_rooms.delete()

    def create_member(self, user, room):
        """Create a room user association"""
        self.remove_member(user, room)
        Message.objects.create_event(user, room, 2)
        m = RoomMember.objects.create(user=user, room=room)

        return m

class RoomMember(models.Model):
    """A room member"""
    room = models.ForeignKey(Room, null=True)
    user = models.ForeignKey(User)

    def save(self, **kw):
        super(RoomMember, self).save(**kw)
    class Meta:
        ordering = ['user']

    objects = memberManager()

def display_timestamp(t):
        """Takes a Unix timestamp as a an arg, returns a text string with
        '<unix timestamp> (<equivalent time>)'."""
        return '%s (%s)' % (t, time.strftime('%d/%m/%Y %H:%M', time.gmtime(t)))

jqchat/templates/jqchat/chat_event.html
<strong>{{ user }}</strong> <em>{{ event }}</em><br />

jqchat/templates/jqchat/chat_message.html
<strong>{{ user }}</strong> {{ msg }}<br/>

jqchat/templates/jqchat/chat_test.html
{% extends "html/base.html" %}
{% load url from future %}

{# An example chat window #}

{% block head_title %}Chat Client{% endblock %}

{% block extra_head %}
<!-- Load the JS for the chat window and start retrieving messages. -->
<script type="text/javascript" src="/static/jqchat/jqchat.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		InitChatWindow("{% url 'jqchat_ajax' room.id %}", null);
	});
</script>
<style type="text/css">
	/* Example styling for the chat window */
   #chatwindow {
     height: 250px;
     width: 400px;
     border: 1px solid;
     padding: 5px;
     margin: 10px 0;
     overflow: auto;
     background-color: white;
     float: left;
   }
  #memberswindow {
     height: 250px;
     width: 100px;
     border: 1px solid;
     padding: 5px;
     margin: 10px 0;
     overflow: auto;
     background-color: white;
     float: left;
   }
 .clear{
     clear: both;
   }
</style>
{% endblock %}

{% block body %}
<div id="chat_left_col">
	<h1>Test Chat Client</h1>
	
	<p>This is a demo of the <a href="http://code.google.com/p/django-jqchat/">
	django-jqchat chat client</a>.</p>
	<p>This page shows the basic client. For an example of how to extend it,
	<a href="{% url 'jqchat_test_window_with_description' room.id %}">see here</a>.</p>
	<p>There are 2 rooms in this demo,
	<a href="{% url 'jqchat_test_window' 1 %}">here</a> and 
	<a href="{% url 'jqchat_test_window' 2 %}">here</a>.</p>
</div>

<h2>Room name: {{ room }}</h2>

<div id="chatwindow"><span id="loading">Loading...</span></div>
<div id="memberswindow"></div>
<div class="clear"></div>
<form id="chatform">
	<label for="msg">Message:</label>
	<input type="text" id="msg" />
	<input type="submit" value="Send message" /><br />
</form>

<script type="text/javascript">
document.getElementById("msg").focus();
</script>

{% endblock %}

jqchat/templates/jqchat/chat_test_with_desc.html
{% extends "html/base.html" %}
{% load url from future %}

{# An example chat window #}

{% block head_title %}Chat Client{% endblock %}

{% block extra_head %}
<!-- Load the JS for the chat window and start retrieving messages. -->
<script type="text/javascript" src="/static/jqchat/jqchat.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		InitChatWindow("{% url 'jqchat_test_window_with_description_ajax' room.id %}", HandleRoomDescription);
		// Initialise the custom code to POST new descriptions.
		InitChatDescription();
	});
</script>
<style type="text/css">
	/* Example styling for the chat window */
   #chatwindow {
     height: 250px;
     width: 400px;
     border: 1px solid;
     padding: 5px;
     margin: 10px 0;
     overflow: auto;
     background-color: white;
     float: left;
   }
   #memberswindow {
     height: 250px;
     width: 100px;
     border: 1px solid;
     padding: 5px;
     margin: 10px 0;
     overflow: auto;
     background-color: white;
     float: left;
   }
 .clear{
     clear: both;
   }
</style>

{% endblock %}

{% block body %}
<div id="chat_left_col">
	<h1>Test Chat Client</h1>
	
	<p>This is a demo of the <a href="http://code.google.com/p/django-jqchat/">
	django-jqchat chat client</a>.</p>
	<p>This page shows how the basic chat client can be extended: the extra field
	<em>room description</em> can be updated from the client window and sent as part
	of the chat client messages. Likewise, updates to the <em>room description</em>
	elsewhere are piggybacked on to the ajax messages received from the server.</p>
	<p>For the basic client,
	<a href="{% url 'jqchat_test_window' room.id %}">see here</a>.</p>
	<p>There are 2 rooms in this demo,
	<a href="{% url 'jqchat_test_window' 1 %}">here</a> and 
	<a href="{% url 'jqchat_test_window' 2 %}">here</a>.</p>
</div>

<h2>Room name: {{ room }}</h2>
<h2>Room description: <span id="chatroom_description"></span></h2>

<div id="chatwindow"><span id="loading">Loading...</span></div>
<div id="memberswindow"></div>
<div class="clear"></div>
<form id="chatform">
	<label for="msg">Message:</label>
	<input type="text" id="msg" />
	<input type="submit" value="Send message" /><br />
</form>

<form id="chatroom_description_form" method="post" action="">
	<label for="id_description">Room description:</label>
	<input id="id_description" type="text" name="description" maxlength="100" />
	<input type="submit" value="Update room description" />
</form>

<script type="text/javascript">document.getElementById("msg").focus();</script>

{% endblock %}